name: Spell Check (FR/EN)

on:
  push:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            **/*.{ts,tsx,js,jsx,md}
            app/**/*.{ts,tsx}
            components/**/*.{ts,tsx}
            data/**/*.{ts,tsx,md}
            docs/**/*.md
          config: ./cspell.json
          check_dot_files: false
          incremental_files_only: false